### ISSUE TITLE
/f info does not return powers

### ISSUE THREAD

**Issue by FrederikFKRasmussen** [LowkeyCoding/factions#9]
### Expected behavior

We expect to see the power after using the command /f info

### Observed/actual behavior

An unexpected error occurred trying to execute that command / by zero

### Steps/models to reproduce

Log in and execute command /f info

### Version

2.0.5

**Comment by LowkeyCoding** [comment]
Seems to be caused by the Point class not being serialized setting the VerticalClaimRange to (0,0) and possibly Faction.useablePower() returning 0. Either way fix is coming very soon.
